config/routes.rb
Rails.application.routes.draw do
  
  get 'scrapper/search'

  resources :expansions


  root to: 'expansions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expansion.rb
class Expansion < ApplicationRecord
  validates :link, uniqueness: {case_sensitive: false ,message: "ya esta registrado"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/expansions_controller.rb
class ExpansionsController < ApplicationController
  before_action :set_expansion, only: [:show, :edit, :update, :destroy]

  # GET /expansions
  # GET /expansions.json

  def index
    require 'open-uri'
 
    url = "http://www.sii.cl/pagina/valores/uf/uf2017.htm"
    html = open(url).read
    time = Time.now
    mes = (time.strftime("%m").to_i) +1
    dia = time.strftime("%d")
     
    @uf = Nokogiri::HTML(html).css("tbody tr[#{dia}] td[#{mes}]").text

    link = open("http://v2.jaidefinichon.com/").read
     
    expansions = Nokogiri::HTML(link).css('.image_post img')


    expansions.each do |exp|
        Expansion.create(
        :link => exp[:src])
    end

    @expansions = Expansion.all
  end

  # GET /expansions/1
  # GET /expansions/1.json
  def show
  end

  # GET /expansions/new
  def new
    @expansion = Expansion.new
  end

  # GET /expansions/1/edit
  def edit
  end

  # POST /expansions
  # POST /expansions.json
  def create
    @expansion = Expansion.new(expansion_params)

    respond_to do |format|
      if @expansion.save
        format.html { redirect_to @expansion, notice: 'Expansion was successfully created.' }
        format.json { render :show, status: :created, location: @expansion }
      else
        format.html { render :new }
        format.json { render json: @expansion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expansions/1
  # PATCH/PUT /expansions/1.json
  def update
    respond_to do |format|
      if @expansion.update(expansion_params)
        format.html { redirect_to @expansion, notice: 'Expansion was successfully updated.' }
        format.json { render :show, status: :ok, location: @expansion }
      else
        format.html { render :edit }
        format.json { render json: @expansion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expansions/1
  # DELETE /expansions/1.json
  def destroy
    @expansion.destroy
    respond_to do |format|
      format.html { redirect_to expansions_url, notice: 'Expansion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expansion
      @expansion = Expansion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expansion_params
      params.require(:expansion).permit(:name, :link)
    end
end

app/controllers/scrapper_controller.rb
class ScrapperController < ApplicationController
  def search
    require 'open-uri'
    year = params[:year]
    html = open("http://www.sii.cl/pagina/valores/uf/uf#{year}.htm").read

    if year

      @result = Nokogiri::HTML(html).css("tbody tr td").text

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expansions_helper.rb
module ExpansionsHelper
end

app/helpers/scrapper_search_helper.rb
module ScrapperSearchHelper
end

app/views/expansions/_form.html.erb
<%= form_for(expansion) do |f| %>
  <% if expansion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expansion.errors.count, "error") %> prohibited this expansion from being saved:</h2>

      <ul>
      <% expansion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expansions/edit.html.erb
<h1>Editing Expansion</h1>

<%= render 'form', expansion: @expansion %>

<%= link_to 'Show', @expansion %> |
<%= link_to 'Back', expansions_path %>

app/views/expansions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expansions</h1>

<h2>UF de hoy: <%= @uf %></h2>

  <% @expansions.each do |exp| %>
    <img class="image" src="<%=  exp.link %>" alt="">
  <% end %>

<br>

<%= link_to 'New Expansion', new_expansion_path %>

app/views/expansions/new.html.erb
<h1>New Expansion</h1>

<%= render 'form', expansion: @expansion %>

<%= link_to 'Back', expansions_path %>

app/views/expansions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @expansion.name %>
</p>

<p>
  <strong>Link:</strong>
  <%= @expansion.link %>
</p>

<%= link_to 'Edit', edit_expansion_path(@expansion) %> |
<%= link_to 'Back', expansions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scrapper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scrapper_search/search.html.erb
<h1>Resultados de busqueda</h1>
<ul>
  <li><%= result %></li>
</ul>